spring:
  profiles:
    active: dev
  application:
    name: SecureBank
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Performance optimizations
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        connection.provider_disables_autocommit: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  main:
    allow-circular-references: true
  # Enable async task execution with larger thread pool
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 100
      thread-name-prefix: secure-bank-async-

# Global SpringDoc configuration for all environments
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    disable-swagger-default-url: true
  paths-to-match: /api/**
  packages-to-scan: com.application.secureBank.Controllers

jwt:
  secret: b2sBUh1/GpSZrRfvxsZY0od6YrqW/iNVYEKylFIQhEtDJ0hgxjGAc5eU48k3ZomX
  expiration: 86400

server:
  port: 8080
  servlet:
    context-path: /
  # Tomcat performance tuning
  tomcat:
    max-threads: 200
    max-connections: 8192
    accept-count: 100
    min-spare-threads: 10

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.secureBank: INFO
    # Log more details for performance monitoring
    com.application.secureBank.Config.PerformanceMonitoringAspect: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7

# Spring Boot 3.x specific settings
spring.threads.virtual.enabled: true