spring:
  profiles:
    active: dev
  application:
    name: SecureBank
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

#  jwt:
#    secret: b2sBUh1/GpSZrRfvxsZY0od6YrqW/iNVYEKylFIQhEtDJ0hgxjGAc5eU48k3ZomX
#    expiration: 86400

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.securebank: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7

# Spring Boot 3.x specific settings
spring.threads.virtual.enabled: true