services:
  # Web service (Spring Boot application)
  - type: web
    name: securebank-api
    plan: standard
    runtime: docker
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: securebank-db
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: securebank-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: securebank-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: kibetbrian258@gmail.com
        sync: false
      - key: MAIL_PASSWORD
        sync: false
#      - key: CORS_ALLOWED_ORIGINS
#        value:

# PostgreSQL Database
databases:
  - name: securebank-db
    plan: standard
    databaseName: securebankdb
    postgresMajorVersion: 15